import type { Metadata } from "next";
<<<<<<< Updated upstream
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
import { Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { systemStatus } from "@/data/system-status";

if (typeof window === "undefined") {
  // Polyfill localStorage for SSR to prevent crashes
  if (
    typeof localStorage === "undefined" ||
    typeof localStorage.getItem !== "function"
  ) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (global as any).localStorage = {
      getItem: () => null,
      setItem: () => { },
      removeItem: () => { },
      clear: () => { },
      length: 0,
      key: () => null,
    };
  }
}

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });
const jetbrainsMono = JetBrains_Mono({ subsets: ["latin"], variable: "--font-mono" });

export const metadata: Metadata = {
  title: systemStatus.name,
  description: systemStatus.role,
  metadataBase: new URL(`https://${systemStatus.domain}`),
  openGraph: {
    title: systemStatus.name,
    description: systemStatus.role,
    url: `https://${systemStatus.domain}`,
    siteName: systemStatus.name,
    type: "website",
  },
>>>>>>> Stashed changes
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
<<<<<<< Updated upstream
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
=======
        className={`${inter.variable} ${jetbrainsMono.variable} font-sans bg-background text-textPrimary antialiased`}
      >
        <Header />
>>>>>>> Stashed changes
        {children}
      </body>
    </html>
  );
}
